Parameters:
  ApiId:
    Type: String
  ApiStage:
    Type: String
  FrontendWebsiteURL:
    Type: String
  RefererSecret:
    Type: String

Resources:

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Logging:
          Bucket: !GetAtt AccessLogs.DomainName
          IncludeCookies: true
        HttpVersion: http2
        CacheBehaviors:
          - ForwardedValues:
              Headers:
                - Password
              QueryString: false
            DefaultTTL: 0
            AllowedMethods: [GET,HEAD,OPTIONS,PUT,POST,PATCH,DELETE]
            PathPattern: api/*
            TargetOriginId: api
            ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          DefaultTTL: 0
          ForwardedValues:
            QueryString: false
          TargetOriginId: frontend
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName: !Sub ${ApiId}.execute-api.${AWS::Region}.amazonaws.com
            Id: api
            OriginPath: !Sub /${ApiStage}
          - Id: frontend
            DomainName: !Select [2, !Split [/, !Ref FrontendWebsiteURL]]
            OriginCustomHeaders:
              - HeaderName: Referer
                HeaderValue: !Ref RefererSecret
            CustomOriginConfig:
              OriginProtocolPolicy: http-only

  AccessLogs:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled