Transform: AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String
  RefererSecret:
    Type: String

Resources:

  Website:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AppName
      LoggingConfiguration:
        DestinationBucketName: !Ref WebsiteAccessLogs
      WebsiteConfiguration:
        IndexDocument: index.js

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Website
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: '*'
            Resource: !Sub ${Website.Arn}/*
            Condition:
              StringLike:
                aws:Referer: !Ref RefererSecret

  WebsiteAccessLogs:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
Outputs:
  WebsiteBucketName:
    Value: !Ref Website
  WebsiteURL:
    Value: !GetAtt Website.WebsiteURL