openapi: 3.0.1

info:
  title: nordshare
  version: 1.0.0
  x-logo:
    url: https://www.freelogodesign.org/file/app/client/thumb/cd0a9e5d-c7c0-4b69-ad0d-4edd4e2aae19_200x200.png?1584650772888
    altText: nordshare
  contact:
    email: tomasz.czubcha@gmail.com

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: all

paths:
  /api/notes:
    post:
      summary: save a note
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Saver.Alias}/invocations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/note'
      responses:
        201:
          description: note saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: id of saved note
                    required: true
                    format: uuid
  /api/notes/{id}:
    get:
      summary: read a note
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Reader.Alias}/invocations
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/password'
      responses:
        200:
          description: note read
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: content of read note
                    required: true
                  ttl:
                    type: number
                    description: minutes left to note expiration
                    required: true

servers:
  - url: https://d2hyhtpm35gjgk.cloudfront.net/{basePath}
    variables:
      basePath:
        default: /api
        description: base path for compability with Cloudfront cache behavior path pattern

components:
  schemas:
    note:
      type: object
      description: note with properties
      properties:
        content:
          type: string
          description: content of note
          minLength: 1
          maxLength: 140
        readPassword:
          type: string
          description: password for read-only access
          minLength: 1
          maxLength: 50
          format: password
          writeOnly: true
        adminPasword:
          type: string
          description: password for note modification
          minLength: 1
          maxLength: 50
          format: password
          writeOnly: true
        ttl:
          type: number
          description: minutes left to note expiration
          minimum: 1
          maximum: 1440
          default: 1440
      required:
        - content
  parameters:
    id:
      in: path
      name: id
      schema:
        type: string
        format: uuid
      required: true
      description: id of a note to read
    password:
      in: header
      name: password
      schema:
        type: string
        format: password
      required: false
      description: read or write a password of a note to read